version: '3.9'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/trade-diary
    command: sh -c "npx prisma db push && node dist/index.js"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
